from __future__ import annotations

from alembic import op
from sqlalchemy import Connection

import mdls.core
from mdls.base.base import Base
from mdls.trgs.trgs import updated_at_trigger
from mdls.funcs.funcs import _quoted_func_name
from mdls.trgs.trgs import _quoted_tg_name
from utils.utils.metadata import _get_tbl, _get_schema

def upgrade() -> None:
    """
    Create `BEFORE UPDATE` triggers on all application tables that have an
    `updated_at` column.

    This migration step is executed when upgrading the database schema. It
    retrieves the list of tables from the SQLAlchemy metadata that contain a
    column named `updated_at` (via `_get_tbl(Base.metadata, has_col='updated_at')`).
    For each such table, it generates a trigger definition using
    `updated_at_trigger()` and executes the resulting SQL statement.

    Each trigger is configured to fire `BEFORE UPDATE` on the table and
    execute the previously created PL/pgSQL function `update_tg` (from the
    `funcs.py` migration). The function sets the `updated_at` column to the
    current timestamp whenever a row is modified, ensuring automatic timestamp
    maintenance.

    The triggers are created in the same schema as the tables, which is derived
    from `Base.metadata` via `_get_schema()`. The function requires an active
    database connection from the Alembic migration context; if none is available,
    a `RuntimeError` is raised.

    Dependencies:
        - The trigger function `update_tg` must exist in the database before
          this migration runs. This migration should therefore be executed
          **after** the migration that creates the function (typically the one
          in `funcs.py`).
        - The target tables must already be created and must have a column
          named `updated_at` of type `TIMESTAMP WITH TIME ZONE` (or a
          compatible type) to avoid errors when the trigger executes.

    Raises:
        RuntimeError: If the Alembic migration context does not provide a
            database connection.

    Notes:
        - The trigger is created without `OR REPLACE`; if a trigger with the
          same name already exists on a table, the migration will fail.
          To avoid conflicts, ensure that any existing triggers are dropped
          first (e.g., during a downgrade) or that trigger names are unique.
        - The trigger name is generated internally by `updated_at_trigger()`
          and typically follows the pattern `update_<table>_tg`.
        - The SQL statements are executed via `op.execute()`, which runs
          within the migration's transaction. In PostgreSQL, `CREATE TRIGGER`
          is transactional, so the entire migration can be rolled back if any
          step fails.
        - This migration is idempotent only if no triggers exist; if you need
          to run it multiple times, consider adding `IF NOT EXISTS` or using
          a `CREATE OR REPLACE` approach, but the current implementation
          assumes a clean upgrade path.
    """
    schema: str = _get_schema(Base.metadata)
    conn: Connection | None = op.get_context().connection
    if conn is None:
        raise RuntimeError("Migration requires an active connection")
    
    for t in _get_tbl(Base.metadata, has_col='updated_at'):
        sql: str = updated_at_trigger(conn, t, schema)
        op.execute(sql)

def downgrade() -> None:
    """
    Drop all `BEFORE UPDATE` triggers that were created by the corresponding
    `upgrade()` migration.

    This migration step is executed when downgrading the database schema. It
    retrieves the complete list of application tables from the SQLAlchemy
    metadata (via `_get_tbl(Base.metadata)`) and, for each table, drops the
    trigger that would have been created in the upgrade step. The trigger name
    is generated by `_quoted_tg_name(conn, t)` and is dropped using a
    `DROP TRIGGER IF EXISTS` statement on the schema‑qualified table name.

    The drop operation is idempotent because of the `IF EXISTS` clause, making
    it safe to run even if the trigger has already been removed or if the
    migration is re‑executed.

    The function requires an active database connection from the Alembic
    context. If the connection is `None`, a `RuntimeError` is raised.

    Important considerations:
        - This downgrade drops **all** triggers on all tables, regardless of
          whether they were created by this migration. If other migrations
          have added additional triggers with the same naming pattern, they
          will also be removed. It is recommended to ensure that the naming
          convention for triggers is unique to this migration or to handle
          them selectively.
        - The table name is quoted using `_quoted_func_name()` (which, despite
          its name, is used here for table quoting). This function ensures
          proper escaping of schema and table identifiers, preventing SQL
          injection and syntax errors.
        - The trigger name is quoted via `_quoted_tg_name()`, which must be
          consistent with the naming logic used in `updated_at_trigger()`
          during the upgrade.
        - Dropping a trigger does **not** affect the underlying table data or
          the `updated_at` column; it only removes the automatic timestamp
          update behavior. Existing `updated_at` values remain unchanged.
        - This migration does not drop the trigger function `update_tg`
          itself; that should be handled by the corresponding `funcs.py`
          downgrade, which must be executed **after** this migration to avoid
          dependency errors.

    Raises:
        RuntimeError: If the Alembic migration context does not provide a
            database connection.
    """
    schema: str = _get_schema(Base.metadata)
    conn: Connection | None = op.get_context().connection
    if conn is None:
            raise RuntimeError("Migration requires an active connection")
    
    for t in _get_tbl(Base.metadata):
        quoted_tbl: str = _quoted_func_name(conn, schema, t)
        quoted_trg: str = _quoted_tg_name(conn, t)
        op.execute(
            f"DROP TRIGGER IF EXISTS {quoted_trg} ON {quoted_tbl};"
        )