from __future__ import annotations

from alembic import op
from sqlalchemy import Connection

from mdls.base.base import Base
from mdls.funcs.funcs import tg_function_updated_at, _quoted_func_name
from utils.utils.metadata import _get_schema

def upgrade() -> None:
    """
    Create a PostgreSQL trigger function that automatically updates a 'updated_at'
    timestamp column on row modification.

    This migration step is executed when upgrading the database schema. It generates
    and executes a SQL statement that creates a stored procedure (trigger function)
    named `update_tg` (or a schema‑qualified variant) in the database. The function
    is intended to be used with `BEFORE UPDATE` triggers on tables that have a
    `updated_at` column of type `TIMESTAMP WITH TIME ZONE`. When invoked, it sets
    the `updated_at` column to the current transaction timestamp (`CURRENT_TIMESTAMP`).

    The function's definition is generated by `tg_function_updated_at()`, which
    constructs a PL/pgSQL function body that is compatible with the target database
    version. The function is created in the schema derived from `Base.metadata`
    (via `_get_schema`), ensuring it resides in the same schema as the application's
    tables.

    The function relies on an active database connection obtained from the Alembic
    migration context. If no connection is available, a `RuntimeError` is raised.

    Raises:
        RuntimeError: If the Alembic migration context does not provide a
            database connection.

    Notes:
        - The function is created without a `CREATE OR REPLACE` clause; if a function
          with the same name and signature already exists, the migration will fail.
          This is intentional to avoid silent overwrites. To safely upgrade, ensure
          that any existing function is dropped first (e.g., in a preceding downgrade)
          or that the function name does not conflict.
        - The SQL is executed directly via `op.execute()`, which runs the statement
          inside the migration's transaction (unless the migration uses a transaction
          that does not support DDL, which is unusual in PostgreSQL).
        - The function assumes that any table using it has a column named `updated_at`
          of type `TIMESTAMP` with time zone. The exact column name is hard‑coded in
          the function body, so it must match the application's convention.
        - This migration should be run before creating any tables that need the
          automatic timestamp update feature.
    """
    conn: Connection | None = op.get_context().connection
    if conn is None:
        raise RuntimeError("Migration requires an active connection")
    
    schema: str = _get_schema(Base.metadata)
    sql: str = tg_function_updated_at(conn, schema)
    op.execute(sql)

def downgrade() -> None:
    """
    Drop the PostgreSQL trigger function `update_tg` that was created by the
    corresponding `upgrade()` migration.

    This migration step is executed when downgrading the database schema. It
    constructs a schema‑qualified name for the function using `_quoted_func_name()`
    and executes a `DROP FUNCTION IF EXISTS ... CASCADE` statement. The `CASCADE`
    option ensures that any triggers that depend on this function are also dropped,
    preventing orphaned dependencies.

    The function is dropped from the schema derived from `Base.metadata`
    (via `_get_schema`). The operation is idempotent because of the `IF EXISTS`
    clause, so it can be safely re‑run even if the function has already been removed.

    The function requires an active database connection from the Alembic context.
    If the connection is `None`, a `RuntimeError` is raised.

    Raises:
        RuntimeError: If the Alembic migration context does not provide a
            database connection.

    Notes:
        - The `CASCADE` option will automatically drop any trigger objects that
          reference this function. This is usually desirable during a downgrade
          because those triggers cannot function without the underlying procedure.
          However, it may cause unintended data loss if triggers are responsible
          for critical logic (e.g., auditing). Ensure that dependent triggers are
          either re‑created later or that their removal is acceptable.
        - The `IF EXISTS` clause prevents an error if the function does not exist,
          making the downgrade safe to run multiple times.
        - The function name is quoted using `_quoted_func_name()`, which handles
          schema qualification and proper escaping of identifiers to avoid SQL
          injection and syntax errors.
        - This downgrade does not explicitly drop any tables or columns; it only
          removes the function. If tables still have triggers that depend on it,
          they will be dropped automatically due to `CASCADE`. However, column
          definitions (e.g., `updated_at`) remain unchanged.
    """
    conn: Connection | None = op.get_context().connection
    if conn is None:
        raise RuntimeError("Migration requires an active connection")
    
    schema: str = _get_schema(Base.metadata)
    quoted_func: str = _quoted_func_name(conn, schema, "update_tg")
    op.execute(f"DROP FUNCTION IF EXISTS {quoted_func} CASCADE;")